import { ProjectData } from "./types";

// Public projects only.
export const ALL_VERCEL_PROJECTS: CuratedProject[] = [
  {
    id: "prj_wWR1ntQQuO2gcZZbgcel2IpTynkl",
    name: "zenfolio",
    url: "https://zenfolio.vercel.app/",
    updatedAt: "2026-02-14T03:38:04.706Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_1OEg1Shie9RRKnikVFcqe1PMqiig",
    name: "ocean-hunter",
    url: "https://ocean-hunter.vercel.app/",
    updatedAt: "2026-02-01T05:51:24.923Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_mWvkuJvGFPx8hiIZo4V0eHEur3Rw",
    name: "yeeder",
    url: "https://yeeder.vercel.app/",
    updatedAt: "2026-01-31T15:48:06.806Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_Kc3xSyVviyWf8BbsEgJaKI0KLjOf",
    name: "majian-game-1",
    url: "https://majian-game-1.vercel.app/",
    updatedAt: "2026-01-29T16:55:46.403Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_2o1nM13GPk2kwybP5415ULTQUf8C",
    name: "quaqualer",
    url: "https://quaqualer.vercel.app/",
    updatedAt: "2026-01-29T16:51:32.880Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_rDaORGsL64ZJpb10Xan1Vo4DutKj",
    name: "write-characters",
    url: "https://write-characters.vercel.app/",
    updatedAt: "2026-01-22T18:43:37.156Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_QCnPt4FE30B2slQdG1O7KhwEiVlO",
    name: "routine-progress",
    url: "https://routine-progress.vercel.app/",
    updatedAt: "2026-01-22T18:23:41.411Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_nmwbECA93hxLXgdrc8VbeuNdwqu6",
    name: "math-crossword",
    url: "https://math-crossword.vercel.app/",
    updatedAt: "2026-01-22T18:22:49.697Z",
    framework: "vite",
    status: "READY",
    featured: true,
  },
  {
    id: "prj_SdDE0mThrGiRZhjXdHcr4ZCNUNMV",
    name: "yeeder1-822k",
    url: "https://yeeder1-822k.vercel.app/",
    updatedAt: "2025-12-24T01:56:19.922Z",
    framework: "Other",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_Xw3lZ4N9YCyjRwEF7bbdHUX8TvRD",
    name: "transpose",
    url: "https://transpose.vercel.app/",
    updatedAt: "2025-11-30T01:12:04.011Z",
    framework: "Other",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_dxwWeJWTOCcepJCN8fnfm2uF0nA4",
    name: "sonic-navigator",
    url: "https://sonic-navigator.vercel.app/",
    updatedAt: "2025-11-19T21:37:06.796Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_UnJ5fGiXgQbYfNglwDyR3040Jc6L",
    name: "echomelo",
    url: "https://echomelo.vercel.app/",
    updatedAt: "2025-11-17T17:29:06.179Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_oHlegQU5Ev53ix8lK1cL5EQxBObL",
    name: "ar-ladder-google1",
    url: "https://ar-ladder-google1.vercel.app/",
    updatedAt: "2025-11-14T17:40:33.525Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_dNguI0COG3Q9bH7QE9PBLqHB0U9k",
    name: "ar-ladder-google",
    url: "https://ar-ladder-google.vercel.app/",
    updatedAt: "2025-11-14T02:45:08.296Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_N4uvOzEW0yc9I5ZKXckAf72sPuOz",
    name: "ar-ladder",
    url: "https://ar-ladder.vercel.app/",
    updatedAt: "2025-11-06T17:10:01.311Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_5vf0nCWye1GE08sM1A8YlM8dswti",
    name: "write-characters-simplified",
    url: "https://write-characters-simplified.vercel.app/",
    updatedAt: "2025-11-02T16:12:18.365Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_VHNKHPV9kgCwsyFyh0P248dNZeGG",
    name: "gpt-ai-assistant",
    url: "https://gpt-ai-assistant.vercel.app/",
    updatedAt: "2025-11-01T13:39:03.980Z",
    framework: "Other",
    status: "READY",
    featured: false,
  },
  {
    id: "prj_eQlbHlPAaBA7B6yQWOo8rWCRKJa4",
    name: "tiptidy-001",
    url: "https://tiptidy-001.vercel.app/",
    updatedAt: "2025-09-10T04:01:20.818Z",
    framework: "vite",
    status: "READY",
    featured: false,
  },
];
